server:
  port: 8082

spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://localhost:5432/course_db
    username: course_user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
